# Generated by Django 5.2.5 on 2025-08-23 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('skill_badges_completed', models.IntegerField(default=0)),
                ('arcade_games_completed', models.IntegerField(default=0)),
                ('trivia_games_completed', models.IntegerField(default=0)),
                ('lab_free_courses_completed', models.IntegerField(default=0)),
                ('access_code_redemption_status', models.CharField(blank=True, max_length=50)),
                ('milestone_earned', models.CharField(blank=True, max_length=50)),
                ('names_of_completed_skill_badges', models.TextField(blank=True)),
                ('names_of_completed_arcade_games', models.TextField(blank=True)),
                ('names_of_completed_trivia_games', models.TextField(blank=True)),
                ('names_of_completed_lab_free_courses', models.TextField(blank=True)),
                ('profile_url_status', models.CharField(blank=True, max_length=100)),
                ('google_cloud_skills_boost_profile_url', models.URLField(blank=True)),
            ],
        ),
    ]
