# Generated by Django 5.2.5 on 2025-08-23 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderboardEntry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='milestone_earned',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
