# Generated by Django 5.2.5 on 2025-08-23 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderboardEntry', '0002_alter_leaderboardentry_milestone_earned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboardentry',
            name='names_of_completed_arcade_games',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='names_of_completed_lab_free_courses',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='names_of_completed_skill_badges',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaderboardentry',
            name='names_of_completed_trivia_games',
            field=models.TextField(blank=True, null=True),
        ),
    ]
