# Generated by Django 5.2.5 on 2025-08-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderboardEntry', '0003_alter_leaderboardentry_names_of_completed_arcade_games_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='closest_milestone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
