# Generated by Django 5.2.5 on 2025-08-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderboardEntry', '0004_leaderboardentry_closest_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='missing_for_closest_milestone',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
