# Generated by Django 5.2.5 on 2025-08-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LeaderboardEntry', '0005_leaderboardentry_missing_for_closest_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='total_points',
            field=models.IntegerField(default=0),
        ),
    ]
